name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  meta: ^1.11.0
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0 
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  mocktail: ^1.0.4
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true


