name: Flutter CI

on: push
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
  format:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format -set-exit-if-changed .
  build:
    runs-on: ubuntu-latest
    env: 
        API_KEY: ${{ secrets.API_KEY }}
        STEND: ${{ secrets.PROD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk —split-per-abi --dart-define=API_KEY={$env:API_KEY} --dart-define=STEND={$env:STEND}
  app_destribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build release 
        run: ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:443444932965:android:e99d4413175e06fbdaf18c
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: task_manager/build/app/outputs/apk/release/app-release.apk